### ISSUE TITLE
May be throw console.error instead console.warn

### ISSUE THREAD

**Issue by srinivasdamam** [siddharthkp/storehook#1]
Here:

https://github.com/siddharthkp/storehook/blob/e066052604b9583cdcfabafdabb340752b87713a/packages/storehook/index.js#L5

**Comment by siddharthkp** [comment]
Sure, do you want to submit a PR?

**Comment by oieduardorabelo** [comment]
i think you can close this one, #3 was merged

**Comment by siddharthkp** [comment]
👍
